# tip baze
quarkus.datasource.db-kind=postgresql

# konekcija na bazu
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Baza1

# login podaci
quarkus.datasource.username=postgres
quarkus.datasource.password=1234

# HTTP port
quarkus.http.port=8081

# Hibernate ORM - automatski update baze
quarkus.hibernate-orm.database.generation=update

# prikaz SQL upita u konzoli
quarkus.hibernate-orm.log.sql=true

# formatiranje SQL-a (?itljivije)
quarkus.hibernate-orm.log.format-sql=true

# inicijalno u?itavanje (preporuka)
quarkus.hibernate-orm.database.generation.create-schemas=true

# KEYCLOAK
quarkus.oidc.auth-server-url=http://localhost:8080/realms/filipprlja
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=realm_access/roles

# SWAGGER
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# REST CLIENTI
quarkus.rest-client.ipify-api.url=https://api.ipify.org
quarkus.rest-client.time-api.url=https://timeapi.io